# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strftime < Formula
  desc "A versatile command-line tool for formatting and manipulating dates, supporting multiple formats and customizable output."
  homepage "https://github.com/zchryr/strftime"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.3/strftime_Darwin_x86_64.tar.gz"
      sha256 "1deaffb757ba93c5ac7dd4c53abd1b625684941c1dcfae85599449cdba034223"

      def install
        bin.install "strftime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.3/strftime_Darwin_arm64.tar.gz"
      sha256 "fde37ac6ade9fb75b3406a376caa75f77d0295c2f1e2b7e97ffc2dca10d1f931"

      def install
        bin.install "strftime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.3/strftime_Linux_arm64.tar.gz"
      sha256 "c43576512a984ee2d33e2f9f54c8dd6d7b9e2a02507dcbaad3dc002c3176ce2f"

      def install
        bin.install "strftime"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.3/strftime_Linux_x86_64.tar.gz"
      sha256 "e8b67a84d972dcf44c922b7fc532d8fc822675fd37c5a1a815ae40ef16ee8017"

      def install
        bin.install "strftime"
      end
    end
  end
end
