# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strftime < Formula
  desc "A versatile command-line tool for formatting and manipulating dates, supporting multiple formats and customizable output."
  homepage "https://github.com/zchryr/strftime"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.2/strftime_Darwin_arm64.tar.gz"
      sha256 "dbd6adc8488e821057594a56d1c7b0805e6e3bbe8e5f4337af457aa268ffb4d7"

      def install
        bin.install "strftime"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.2/strftime_Darwin_x86_64.tar.gz"
      sha256 "8aeafb8272ad1f7ce9d6b4f580383069e6ada772825dcd891eeda4f74336d6dd"

      def install
        bin.install "strftime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.2/strftime_Linux_x86_64.tar.gz"
      sha256 "8e4a87a49a1c32e7ea30e9af004b4c2873f145437b671fec970767cfaace4939"

      def install
        bin.install "strftime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zchryr/strftime/releases/download/v0.0.2/strftime_Linux_arm64.tar.gz"
      sha256 "d833125bc5cc0aa119daedadf70fb80d4e80f9cb5d989f09b63e6c5e9dd752ee"

      def install
        bin.install "strftime"
      end
    end
  end
end
